import numpy as np

a= np.arange(10)
print(f"ndarray: \n{a}\n")

print(f"a[0]: ", a[0])
print(f"a[2]: ", a[2])
print()
print(f"a[-1]: ", a[-1])
print(f"a[-2]: ", a[-2])
print()
print(f"a[0:3]: ", a[0:3])
print(f"a[3:7]: ", a[3:7])
print(f"a[5:-1]: ", a[5:-1])
print()
print(f"a[2:]: ", a[2:])
print(f"a[-2:]: ", a[-2:])
print(f"a[:-3]: ", a[:-3])
print(f"a[:]: ", a[:])
print()
print(f"a[2:7:2]: ", a[2:7:2])
print(f"a[::3]: ", a[::3])
print()
print(f"a[7:2:-1]: ", a[7:2:-1])
print(f"a[::-1]: ", a[::-1])
print(f"a[8:3:-2]: ", a[8:3:-2])
print(f"a[::-3]: ", a[::-3])